# Generated by Django 2.0.4 on 2018-05-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('contact_num', models.CharField(max_length=60)),
                ('rates', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LightsAndSounds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('contact_num', models.CharField(max_length=60)),
                ('rates', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('image_url', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=60)),
                ('contact_num', models.CharField(max_length=60)),
                ('capacity', models.CharField(max_length=100)),
                ('rates', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
            ],
        ),
    ]
